# Copyrights (c) 2018 Jeremy Savonet

dist: trusty

sudo: required

language:
  - cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake

before_install:
  - cd
  - git clone --depth=1 --branch=5.2.1 https://github.com/JeremySavonet/JUCE.git
  - git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
  - cd vst3sdk && git checkout vstsdk367_03_03_2017_build_352
  - git submodule update --recursive
  - pwd

# Build steps
script:
  - cd ${TRAVIS_BUILD_DIR}/Builds/CLion
  - pwd
  - mkdir cmake-build-debug && cd cmake-build-debug
  - pwd
  - cmake ..
    #- make STANDALONE_PLUGIN
